#!/bin/sh

# save the file as /etc/initramfs-tools/hooks/iot_isl_hook
set -e

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /home/zer0/Desktop/kichu/IOT_isl/dameon/secureBoot/version2/verifier \
          /usr/local/bin/verifier

cp /home/zer0/Desktop/kichu/IOT_isl/dameon/secureBoot/version2/secureBoot.boot \
   "${DESTDIR}/secureBoot.boot"
